// <auto-generated />
namespace projetoposPedroTelles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updated2C : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated2C));
        
        string IMigrationMetadata.Id
        {
            get { return "201709100601088_updated-2-C"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
